name: phntmxyz_bump_version_sidekick_plugin
description: Generated sidekick plugin (template shared-command)
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  sidekick_core: ^1.0.0
  posix: ^3.0.0

dev_dependencies:
  lint: ^1.5.0
  sidekick_plugin_installer: ^0.3.0
  sidekick_test:
    git:
      url: https://github.com/phntmxyz/sidekick
      path: sidekick_test
      ref: sidekick_core-v1.1.0
  test: ^1.20.0