name: phntmxyz_bump_version_sidekick_plugin
description: Generated sidekick plugin (template shared-command)
version: 1.2.1
repository: https://github.com/phntmxyz/bump_version_sidekick_plugin
issue_tracker: https://github.com/phntmxyz/bump_version_sidekick_plugin/issues
topics:
  - sidekick
  - cli
  - sidekick-plugin

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  pubspec_manager: ^1.0.2
  sidekick_core: ^3.0.0-preview.6
  yaml_edit: ^2.1.0

dev_dependencies:
  lint: ^2.0.0
  sidekick_plugin_installer: ^1.3.0
  sidekick_test:
    git:
      url: https://github.com/phntmxyz/sidekick
      path: sidekick_test
  test: ^1.20.0