name: phntmxyz_bump_version_sidekick_plugin
description: Generated sidekick plugin (template shared-command)
version: 1.0.0
repository: https://github.com/phntmxyz/bump_version_sidekick_plugin
issue_tracker: https://github.com/phntmxyz/bump_version_sidekick_plugin/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  sidekick_core: ^1.0.0

dev_dependencies:
  lint: ^1.5.0
  sidekick_plugin_installer: ^0.3.0
  sidekick_test:
    git:
      url: https://github.com/phntmxyz/sidekick
      path: sidekick_test
      ref: f244dc3
  test: ^1.20.0