name: Dart Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    container:
      image: dart:3.0.2

    steps:
      - uses: actions/checkout@v1
      - name: check formatting
        run: |
          dart format --fix --output none --set-exit-if-changed .