name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Every night at 03:00
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  integration_tests_linux_local:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Always keep support to at least 2 stable versions
        version: [ "3.5.0", "latest" ]

    container:
      image: dart:${{ matrix.version }}

    steps:
      - run: |
          apt-get update
          apt-get install unzip
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get --no-precompile
      - name: Run with latest sidekick from pub
        run: |
          set -o errexit
          
          # install sidekick
          dart pub global activate sidekick
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          
          # prepare test package
          cd ..
          mkdir tmp
          cd tmp
          echo 'name: tmp\nversion: 1.2.3' > pubspec.yaml
          
          # create sidekick CLI for test package and install phntmxyz_bump_version_sidekick_plugin
          sidekick init --cliName dashi --projectRoot . --cliPackageDirectory .
          ./dashi -h
          ./dashi sidekick plugins install -s path ../bump_version_sidekick_plugin
          
          # call bump-version command and check result
          ./dashi bump-version --major .
          grep -Rq 'version: 2.0.0' pubspec.yaml
          
