name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Every night at 03:00
    - cron: '0 3 * * *'

jobs:
  integration_tests_linux_local:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Always keep support to at least 2 stable versions
        version: [ "2.14", "2.15", "2.16", "2.17", "2.18", "latest" ]

    container:
      image: dart:${{ matrix.version }}

    steps:
      - run: |
          apt-get update
          apt-get install unzip
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get --no-precompile
      - name: Run tests
        run: dart test
      - name: Run with latest sidekick from pub
        run: |
          set -o errexit
          dart pub global activate sidekick
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          cd ..
          mkdir tmp
          cd tmp
          sidekick init --cliName dashi --projectRoot . --cliPackageDirectory .
          ./dashi -h
          ./dashi sidekick plugins install -s path $HOME
          ./dashi bump-version --major
