name: Dart Analyzer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: dart:3.8.1

    steps:
      - uses: actions/checkout@v4    

      - name: Install pub packages
        run: dart pub get

      - name: lint
        run: dart analyze --fatal-infos .