name: Dart Analyzer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: dart:3.8.1

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get
      - name: lint
        run: dart analyze --fatal-infos .