name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Always keep support to at least 2 stable versions
        version: [ "3.0", "latest" ]

    container:
      image: dart:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: |
          git config --global user.email "dash@flutter.dev"
          git config --global user.name "Dash"
          dart test
