name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    container:
      image: dart:2.18.6

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
